# Generated by Django 3.0.4 on 2020-07-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_input1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlineide',
            options={'ordering': ('created_at',)},
        ),
    ]
