# Generated by Django 3.0.4 on 2020-07-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_auto_20200730_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlineide',
            options={'ordering': ('-created_at',)},
        ),
    ]
